# Lookup tables for USPS-style address standardization.
# Suffix/directional abbreviations follow USPS Publication 28.

STATE_ABBR = {
    "ALABAMA": "AL", "ALASKA": "AK", "ARIZONA": "AZ", "ARKANSAS": "AR",
    "CALIFORNIA": "CA", "COLORADO": "CO", "CONNECTICUT": "CT", "DELAWARE": "DE",
    "DISTRICT OF COLUMBIA": "DC", "FLORIDA": "FL", "GEORGIA": "GA", "HAWAII": "HI",
    "IDAHO": "ID", "ILLINOIS": "IL", "INDIANA": "IN", "IOWA": "IA",
    "KANSAS": "KS", "KENTUCKY": "KY", "LOUISIANA": "LA", "MAINE": "ME",
    "MARYLAND": "MD", "MASSACHUSETTS": "MA", "MICHIGAN": "MI", "MINNESOTA": "MN",
    "MISSISSIPPI": "MS", "MISSOURI": "MO", "MONTANA": "MT", "NEBRASKA": "NE",
    "NEVADA": "NV", "NEW HAMPSHIRE": "NH", "NEW JERSEY": "NJ", "NEW MEXICO": "NM",
    "NEW YORK": "NY", "NORTH CAROLINA": "NC", "NORTH DAKOTA": "ND", "OHIO": "OH",
    "OKLAHOMA": "OK", "OREGON": "OR", "PENNSYLVANIA": "PA", "RHODE ISLAND": "RI",
    "SOUTH CAROLINA": "SC", "SOUTH DAKOTA": "SD", "TENNESSEE": "TN", "TEXAS": "TX",
    "UTAH": "UT", "VERMONT": "VT", "VIRGINIA": "VA", "WASHINGTON": "WA",
    "WEST VIRGINIA": "WV", "WISCONSIN": "WI", "WYOMING": "WY",
}

DIRECTIONALS = {
    "NORTH": "N", "SOUTH": "S", "EAST": "E", "WEST": "W",
    "NORTHEAST": "NE", "NORTHWEST": "NW", "SOUTHEAST": "SE", "SOUTHWEST": "SW",
}

# Full USPS Pub 28 Appendix C1 standard suffix list: primary spelling and
# common alternate spellings, all mapped to the one abbreviation USPS
# expects on a mail piece.
STREET_SUFFIXES = {
    "ALLEY": "ALY", "ALLEE": "ALY", "ALLY": "ALY",
    "ANEX": "ANX", "ANNEX": "ANX", "ANNX": "ANX",
    "ARCADE": "ARC",
    "AVENUE": "AVE", "AV": "AVE", "AVEN": "AVE", "AVENU": "AVE",
    "AVN": "AVE", "AVNUE": "AVE",
    "BAYOO": "BYU", "BAYOU": "BYU",
    "BEACH": "BCH",
    "BEND": "BND",
    "BLUFF": "BLF", "BLUFFS": "BLFS",
    "BOTTOM": "BTM", "BOT": "BTM", "BOTTM": "BTM",
    "BOULEVARD": "BLVD", "BOUL": "BLVD", "BOULV": "BLVD",
    "BRANCH": "BR", "BRNCH": "BR",
    "BRIDGE": "BRG", "BRDGE": "BRG",
    "BROOK": "BRK", "BROOKS": "BRKS",
    "BURG": "BG", "BURGS": "BGS",
    "BYPASS": "BYP", "BYPA": "BYP", "BYPAS": "BYP", "BYPS": "BYP",
    "CAMP": "CP", "CMP": "CP",
    "CANYON": "CYN", "CANYN": "CYN", "CNYN": "CYN",
    "CAPE": "CPE",
    "CAUSEWAY": "CSWY", "CAUSWA": "CSWY",
    "CENTER": "CTR", "CEN": "CTR", "CENT": "CTR", "CENTR": "CTR",
    "CENTRE": "CTR", "CNTER": "CTR", "CNTR": "CTR", "CTER": "CTR",
    "CENTERS": "CTRS",
    "CIRCLE": "CIR", "CIRC": "CIR", "CIRCL": "CIR", "CRCL": "CIR", "CRCLE": "CIR",
    "CIRCLES": "CIRS",
    "CLIFF": "CLF", "CLIFFS": "CLFS",
    "CLUB": "CLB",
    "COMMON": "CMN", "COMMONS": "CMNS",
    "CORNER": "COR", "CORNERS": "CORS",
    "COURSE": "CRSE",
    "COURT": "CT", "COURTS": "CTS",
    "COVE": "CV", "COVES": "CVS",
    "CREEK": "CRK",
    "CRESCENT": "CRES", "CRSENT": "CRES", "CRSNT": "CRES",
    "CREST": "CRST",
    "CROSSING": "XING", "CRSSNG": "XING",
    "CROSSROAD": "XRD", "CROSSROADS": "XRDS",
    "CURVE": "CURV",
    "DALE": "DL",
    "DAM": "DM",
    "DIVIDE": "DV", "DIV": "DV", "DVD": "DV",
    "DRIVE": "DR", "DRIV": "DR", "DRV": "DR",
    "DRIVES": "DRS",
    "ESTATE": "EST", "ESTATES": "ESTS",
    "EXPRESSWAY": "EXPY", "EXP": "EXPY",
    "EXTENSION": "EXT", "EXTN": "EXT", "EXTNSN": "EXT",
    "EXTENSIONS": "EXTS",
    "FALL": "FALL", "FALLS": "FLS",
    "FERRY": "FRY", "FRRY": "FRY",
    "FIELD": "FLD", "FIELDS": "FLDS",
    "FLAT": "FLT", "FLATS": "FLTS",
    "FORD": "FRD", "FORDS": "FRDS",
    "FOREST": "FRST",
    "FORGE": "FRG", "FORG": "FRG", "FORGES": "FRGS",
    "FORK": "FRK", "FORKS": "FRKS",
    "FORT": "FT", "FRT": "FT",
    "FREEWAY": "FWY", "FREEWY": "FWY", "FRWAY": "FWY", "FRWY": "FWY",
    "GARDEN": "GDN", "GARDN": "GDN", "GRDEN": "GDN", "GRDN": "GDN",
    "GARDENS": "GDNS", "GRDNS": "GDNS",
    "GATEWAY": "GTWY", "GATEWY": "GTWY", "GATWAY": "GTWY", "GTWAY": "GTWY",
    "GLEN": "GLN", "GLENS": "GLNS",
    "GREEN": "GRN", "GREENS": "GRNS",
    "GROVE": "GRV", "GROV": "GRV", "GROVES": "GRVS",
    "HARBOR": "HBR", "HARB": "HBR", "HARBR": "HBR", "HRBOR": "HBR",
    "HARBORS": "HBRS",
    "HAVEN": "HVN",
    "HEIGHTS": "HTS",
    "HIGHWAY": "HWY", "HIGHWY": "HWY", "HIWAY": "HWY", "HIWY": "HWY", "HWAY": "HWY",
    "HILL": "HL", "HILLS": "HLS",
    "HOLLOW": "HOLW", "HOLLOWS": "HOLW", "HOLWS": "HOLW",
    "INLET": "INLT",
    "ISLAND": "IS", "ISLND": "IS",
    "ISLANDS": "ISS", "ISLNDS": "ISS",
    "ISLE": "ISLE",
    "JUNCTION": "JCT", "JCTION": "JCT", "JCTN": "JCT", "JUNCTN": "JCT", "JUNCTON": "JCT",
    "JUNCTIONS": "JCTS",
    "KEY": "KY", "KEYS": "KYS",
    "KNOLL": "KNL", "KNOL": "KNL", "KNOLLS": "KNLS",
    "LAKE": "LK", "LAKES": "LKS",
    "LAND": "LAND",
    "LANDING": "LNDG", "LNDNG": "LNDG",
    "LANE": "LN",
    "LIGHT": "LGT", "LIGHTS": "LGTS",
    "LOAF": "LF",
    "LOCK": "LCK", "LOCKS": "LCKS",
    "LODGE": "LDG", "LDGE": "LDG", "LODG": "LDG",
    "LOOP": "LOOP",
    "MALL": "MALL",
    "MANOR": "MNR", "MANORS": "MNRS",
    "MEADOW": "MDW", "MEADOWS": "MDWS", "MEDOWS": "MDWS",
    "MEWS": "MEWS",
    "MILL": "ML", "MILLS": "MLS",
    "MISSION": "MSN",
    "MOTORWAY": "MTWY",
    "MOUNT": "MT", "MNT": "MT",
    "MOUNTAIN": "MTN", "MNTAIN": "MTN", "MNTN": "MTN",
    "MOUNTAINS": "MTNS",
    "NECK": "NCK",
    "ORCHARD": "ORCH", "ORCHRD": "ORCH",
    "OVAL": "OVAL", "OVL": "OVAL",
    "OVERPASS": "OPAS",
    "PARK": "PARK", "PRK": "PARK", "PARKS": "PARK",
    "PARKWAY": "PKWY", "PARKWY": "PKWY", "PKWAY": "PKWY", "PKY": "PKWY",
    "PASS": "PASS",
    "PASSAGE": "PSGE",
    "PATH": "PATH",
    "PIKE": "PIKE",
    "PINE": "PNE", "PINES": "PNES",
    "PLACE": "PL",
    "PLAIN": "PLN", "PLAINS": "PLNS",
    "PLAZA": "PLZ", "PLZA": "PLZ",
    "POINT": "PT", "POINTS": "PTS",
    "PORT": "PRT", "PORTS": "PRTS",
    "PRAIRIE": "PR", "PRARIE": "PR", "PRR": "PR",
    "RADIAL": "RADL", "RAD": "RADL", "RADIEL": "RADL",
    "RAMP": "RAMP",
    "RANCH": "RNCH", "RANCHES": "RNCH",
    "RAPID": "RPD", "RAPIDS": "RPDS",
    "REST": "RST",
    "RIDGE": "RDG", "RDGE": "RDG", "RIDGES": "RDGS",
    "RIVER": "RIV", "RIVR": "RIV", "RVR": "RIV",
    "ROAD": "RD", "ROADS": "RDS",
    "ROUTE": "RTE",
    "ROW": "ROW",
    "RUE": "RUE",
    "RUN": "RUN",
    "SHOAL": "SHL", "SHOALS": "SHLS",
    "SHORE": "SHR", "SHORES": "SHRS",
    "SKYWAY": "SKWY",
    "SPRING": "SPG", "SPNG": "SPG", "SPRNG": "SPG",
    "SPRINGS": "SPGS",
    "SPUR": "SPUR",
    "SQUARE": "SQ", "SQR": "SQ", "SQRE": "SQ", "SQU": "SQ",
    "SQUARES": "SQS",
    "STATION": "STA", "STATN": "STA", "STN": "STA",
    "STRAVENUE": "STRA", "STRAV": "STRA", "STRAVEN": "STRA",
    "STRAVN": "STRA", "STRVN": "STRA", "STRVNUE": "STRA",
    "STREAM": "STRM",
    "STREET": "ST", "STRT": "ST", "STR": "ST",
    "STREETS": "STS",
    "SUMMIT": "SMT", "SUMIT": "SMT", "SUMITT": "SMT",
    "TERRACE": "TER", "TERR": "TER",
    "THROUGHWAY": "TRWY",
    "TRACE": "TRCE",
    "TRACK": "TRAK",
    "TRAFFICWAY": "TRFY",
    "TRAIL": "TRL",
    "TRAILER": "TRLR",
    "TUNNEL": "TUNL", "TUNEL": "TUNL", "TUNLS": "TUNL", "TUNNL": "TUNL",
    "TURNPIKE": "TPKE", "TRNPK": "TPKE",
    "UNDERPASS": "UPAS",
    "UNION": "UN",
    "VALLEY": "VLY", "VALLY": "VLY", "VLLY": "VLY",
    "VIADUCT": "VIA", "VDCT": "VIA", "VIADCT": "VIA",
    "VIEW": "VW", "VIEWS": "VWS",
    "VILLAGE": "VLG", "VILL": "VLG", "VILLAG": "VLG", "VILLG": "VLG", "VILLIAGE": "VLG",
    "VILLAGES": "VLGS",
    "VILLE": "VL",
    "VISTA": "VIS", "VIST": "VIS", "VST": "VIS", "VSTA": "VIS",
    "WALK": "WALK", "WALKS": "WALK",
    "WALL": "WALL",
    "WAY": "WAY",
    "WELL": "WL", "WELLS": "WLS",
}

UNIT_DESIGNATORS = {
    "APARTMENT": "APT", "BUILDING": "BLDG", "DEPARTMENT": "DEPT",
    "FLOOR": "FL", "ROOM": "RM", "SUITE": "STE", "UNIT": "UNIT",
}
